module.exports = {
  singleQuote: true,
  trailingComma: 'es5',
  printWidth: 100,
  importOrder: [
    '^react$',
    '^react',
    '^classnames',
    '^@mui/(.*)|^@auth0/(.*)|^dayjs',
    '^@storybook/(.*)',
    '^lodash',
    'hooks',
    'utils',
    'api',
    'signals',
    'pages',
    'containers',
    '.container$',
    'views',
    'testID',
    '^types',
    '^enums',
    '^themes',
    '^commonConstants',
    'Internals',
    '^./(.*)view$',
    '^../(.*)view$',
    '^./(.*)scss$',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true
};
